import localFont from "next/font/local";
import "./globals.css";
import { Lato } from "next/font/google";

export const metadata = {
  title: "Tasker",
  description: "Generated by create next app",
};
const clash_bold = localFont({
  src: "../public/font/ClashDisplayBold.otf",
  variable: "--font-clash_bold",
});
const clash_regular = localFont({
  src: "../public/font/ClashDisplayRegular.otf",
  variable: "--font-clash_regular",
});
const clash_semibold = localFont({
  src: "../public/font/ClashDisplaySemibold.otf",
  variable: "--font-clash_semibold",
});
const clash_medium = localFont({
  src: "../public/font/ClashDisplayMedium.otf",
  variable: "--font-clash_medium",
});
const clash_extralight = localFont({
  src: "../public/font/ClashDisplayExtralight.otf",
  variable: "--font-clash_extralight",
});
const lato = Lato({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["100", "300", "400", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${clash_bold.variable} ${clash_regular.variable} ${clash_medium.variable} ${clash_semibold.variable} ${clash_extralight.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
